[package]

name = "rust-caliburn"
version = "0.0.1"
authors = ["cepheus"]

# Blocked until libsyntax and new collections are frozen
# [dependencies.peg]
# git = "https://github.com/kevinmehall/rust-peg.git"
